export const AVAILABILITY_LABELS = {
  availability_create: 'Create Availability',
  create_availability: 'Create Availability',
  manage_availabilities: 'Manage Availabilities',
  select_truck: 'Select Truck',
  origin_state: 'Origin State',
  origin_city: 'Origin City',
  destination_state: 'Destination State',
  destination_city: 'Destination City',
  available_from: 'Available From',
  available_till: 'Available Till',
  field_required: 'is required',
  required_marker: '*',
  select_date: 'Select Date',
  date_placeholder: 'YYYY-MM-DD',
  select_placeholder: 'Select…',
  create: 'Create',
  created_success: 'Availability created successfully.',
  required_error: 'Please fill all required fields.',
  date_range_error: 'Available Till must be on or after Available From.',
  load_error: 'Could not load data.',
  save_error: 'Could not save. Please try again.',
  error_overlap_title: 'Availability Conflict',
  error_overlap_message:
    'This truck already has an availability for selected dates. Cancel existing availability to continue.',
  error_invalid_date_title: 'Invalid Date',
  error_past_date: 'Past dates are not allowed.',
  truck: 'Truck',
  category: 'Category',
  capacity: 'Capacity',
  gps: 'GPS',
  verification_status: 'Verification Status',
  origin: 'Origin',
  destination: 'Destination',
  yes: 'Yes',
  no: 'No',
  no_availabilities: 'No availabilities yet.',
  confirm: 'OK',
  close_availability: 'Close Availability',
  cancel_availability: 'Cancel Availability',
  confirm_action_title: 'Confirm Action',
  confirm_close_message: 'Are you sure you want to close this availability?',
  confirm_cancel_message: 'Are you sure you want to cancel this availability?',
  cancel: 'Cancel',
  status: 'Status',
  status_available: 'Available',
  status_closed: 'Closed',
  status_cancelled: 'Cancelled',
  already_closed: 'This availability is already closed.',
  already_cancelled: 'This availability is already cancelled.',
} as const;
