/**
 * Truck UI copy — use in truck screens/cards only (no hardcoded strings in components).
 */
export const LABELS = {
  category: 'Category',
  variant_id: 'Variant',
  capacity_tons: 'Capacity',
  variant: 'Variant',
  capacity: 'Capacity',
  permit_type: 'Permit type',
  axle_count: 'Axle count',
  wheel_count: 'Wheel count',
  gps_available: 'GPS available',
  required_marker: '*',
  required_note: 'These fields are required',
  required_field_error: 'This field is required.',
  verification_status: 'Verification Status',
  verify: 'Verify',
  add_truck: 'Add Truck',
  manage_trucks: 'Manage Trucks',
  edit_truck: 'Edit Truck',
  save: 'Save',
  submit: 'Submit',
  select_placeholder: 'Select…',
  no_trucks: 'No trucks yet.',
  load_error: 'Could not load data.',
  save_error: 'Could not save. Please try again.',
  truck_added: 'Truck added successfully.',
  truck_updated: 'Truck updated successfully.',
  variant_name: 'Variant',
  edit: 'Edit',
  delete: 'Delete',
  confirm_delete_title: 'Confirm Delete',
  confirm_delete_message: 'Are you sure you want to delete this truck?',
  cancel: 'Cancel',
  confirm: 'Delete',
  cannot_edit_pending: 'Cannot edit a truck under verification approval',
  cannot_edit_verified:
    'You cannot edit verified trucks. To edit this truck, delete it and add a new truck',
  edit_not_allowed_title: 'Edit Not Allowed',
  truck_deleted: 'Truck deleted successfully.',
  delete_error: 'Could not delete truck. Please try again.',
} as const;
